name: TEST
hosts: all
tasks:
  - name: Execute command
    command: date

  - name: Run the equivalent of "pacman -Syu" as a separate step
    community.general.pacman:
     update_cache: yes
     upgrade: yes  