---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name: 
      - htop
      - nano
      - wget
      - mc
  - name: Add Sngrep repository
    yum_repository:
      name: irontec
      description: Irontec RPMs repository
      baseurl: http://packages.irontec.com/centos/$releasever/$basearch/
      state: present
  - name: rpm key for sngrep repo
    rpm_key: state=present key=http://packages.irontec.com/public.key
  - name: install sngrep
    yum: name=sngrep state=latest #update_cache=true